version: '3.9'

services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -dbPath /home/dynamodblocal/data/"
    image: "amazon/dynamodb-local:latest"
    user: root
    ports:
      - 9000:8000
    volumes:
      - dynamo_data:/home/dynamodblocal/data

  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379

  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "localstack_data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  webserver:
    image: "nginx:alpine-slim"
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d/


volumes:
  dynamo_data:
  localstack_data:
