#!/bin/bash
set -e

[ ! "$VIRTUAL_ENV" -ef ./venv ] && source venv/bin/activate

if [ ! -f "dist/layer-numpy-manylinux2014_aarch64.zip" ]
then
    echo Packaging numpy layer

    [ -d package/numpy ] && rm -Rf package/numpy
    pip install -t package/numpy/python  --platform=manylinux2014_aarch64 --only-binary=:all: numpy

    [ ! -d dist ] && mkdir dist
    pushd package/numpy
    zip -r ../../dist/layer-numpy-manylinux2014_aarch64.zip . 
    popd
fi

echo Building dotsboxes package
python -m build
dots_package=$(find dist -name 'dotsboxes-*.tar.gz')

echo Packaging lambda
[ -d package/lambda ] && rm -Rf package/lambda
pip install --no-deps -t package/lambda $dots_package
cp src/lambda/dblambda.py package/lambda

pushd package/lambda
zip -r ../../dist/lambda-dotsboxes.zip . -x "*/__pycache__/*"

