AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  Create DynamoDB table for storing game session information.
Resources:
  dotsboxesGameSessions:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions:
        - AttributeName: 'id'
          AttributeType: 'S'
#        - AttributeName: 'game'
#          AttributeType: 'B'
#        - AttributeName: 'p1'
#          AttributeType: 'S'
#        - AttributeName: 'p2'
#          AttributeType: 'S'
#        - AttributeName: 'v'
#          AttributeType: 'N'
      BillingMode: 'PAY_PER_REQUEST'
      KeySchema:
        - AttributeName: 'id'
          KeyType: HASH
Outputs:
  GamesSessionsTableName:
    Value: !Ref dotsboxesGameSessions
    Description: Table name of the newly created DynamoDB table
